package com.testing.carregister.models.user;

public enum ERegion {
    AN_GIANG,
    BA_RIA_VUNG_TAU,
    BAC_LIEU,
    BAC_GIANG,
    BAC_KAN,
    BAC_NINH,
    BEN_TRE,
    BINH_DUONG,
    BINH_DINH,
    BINH_PHUOC,
    BINH_THUAN,
    CA_MAU,
    CAO_BANG,
    CAN_THO,
    DA_NANG,
    DAK_LAK,
    DAK_NONG,
    DIEN_BIEN,
    DONG_NAI,
    DONG_THAP,
    GIA_LAI,
    HA_GIANG,
    HA_NAM,
    HA_NOI,
    HA_TINH,
    HAI_DUONG,
}
